### ISSUE TITLE
Mono.Cecil.AssemblyResolutionException when building

### ISSUE THREAD

**Issue by KnuniK** [vlgs/Unity-Barracuda-U2-Net-HoloLens#3]
When building your project I get the Error:
`Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'`

Any Idea what could cause that error?

**Comment by vlgs** [comment]
Sorry I just saw your issue. Try to update the minimum or taget Windows SDK your are using.
